// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventHeader_EventType int32

const (
	EventHeader_UNKNOWN EventHeader_EventType = 0
	EventHeader_Event1  EventHeader_EventType = 1
	EventHeader_Event2  EventHeader_EventType = 2
	EventHeader_Event3  EventHeader_EventType = 3
	EventHeader_Event4  EventHeader_EventType = 4
	EventHeader_Event5  EventHeader_EventType = 5
)

var EventHeader_EventType_name = map[int32]string{
	0: "UNKNOWN",
	1: "Event1",
	2: "Event2",
	3: "Event3",
	4: "Event4",
	5: "Event5",
}

var EventHeader_EventType_value = map[string]int32{
	"UNKNOWN": 0,
	"Event1":  1,
	"Event2":  2,
	"Event3":  3,
	"Event4":  4,
	"Event5":  5,
}

func (x EventHeader_EventType) String() string {
	return proto.EnumName(EventHeader_EventType_name, int32(x))
}

func (EventHeader_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2, 0}
}

type Event struct {
	Header               *EventHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *EventBody   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetHeader() *EventHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Event) GetBody() *EventBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type EventBody struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventBody) Reset()         { *m = EventBody{} }
func (m *EventBody) String() string { return proto.CompactTextString(m) }
func (*EventBody) ProtoMessage()    {}
func (*EventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *EventBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventBody.Unmarshal(m, b)
}
func (m *EventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventBody.Marshal(b, m, deterministic)
}
func (m *EventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBody.Merge(m, src)
}
func (m *EventBody) XXX_Size() int {
	return xxx_messageInfo_EventBody.Size(m)
}
func (m *EventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBody.DiscardUnknown(m)
}

var xxx_messageInfo_EventBody proto.InternalMessageInfo

func (m *EventBody) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type EventHeader struct {
	Version              int32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	DeviceCode           string                `protobuf:"bytes,2,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	Date                 *timestamp.Timestamp  `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	EventType            EventHeader_EventType `protobuf:"varint,4,opt,name=eventType,proto3,enum=proto.EventHeader_EventType" json:"eventType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EventHeader) Reset()         { *m = EventHeader{} }
func (m *EventHeader) String() string { return proto.CompactTextString(m) }
func (*EventHeader) ProtoMessage()    {}
func (*EventHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *EventHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventHeader.Unmarshal(m, b)
}
func (m *EventHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventHeader.Marshal(b, m, deterministic)
}
func (m *EventHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventHeader.Merge(m, src)
}
func (m *EventHeader) XXX_Size() int {
	return xxx_messageInfo_EventHeader.Size(m)
}
func (m *EventHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_EventHeader.DiscardUnknown(m)
}

var xxx_messageInfo_EventHeader proto.InternalMessageInfo

func (m *EventHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EventHeader) GetDeviceCode() string {
	if m != nil {
		return m.DeviceCode
	}
	return ""
}

func (m *EventHeader) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *EventHeader) GetEventType() EventHeader_EventType {
	if m != nil {
		return m.EventType
	}
	return EventHeader_UNKNOWN
}

type File struct {
	ContentType          int32                `protobuf:"varint,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Category             int32                `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	Data                 []byte               `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetContentType() int32 {
	if m != nil {
		return m.ContentType
	}
	return 0
}

func (m *File) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *File) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DebugMessage struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugMessage) Reset()         { *m = DebugMessage{} }
func (m *DebugMessage) String() string { return proto.CompactTextString(m) }
func (*DebugMessage) ProtoMessage()    {}
func (*DebugMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}

func (m *DebugMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugMessage.Unmarshal(m, b)
}
func (m *DebugMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugMessage.Marshal(b, m, deterministic)
}
func (m *DebugMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugMessage.Merge(m, src)
}
func (m *DebugMessage) XXX_Size() int {
	return xxx_messageInfo_DebugMessage.Size(m)
}
func (m *DebugMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DebugMessage proto.InternalMessageInfo

func (m *DebugMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("proto.EventHeader_EventType", EventHeader_EventType_name, EventHeader_EventType_value)
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*EventBody)(nil), "proto.EventBody")
	proto.RegisterType((*EventHeader)(nil), "proto.EventHeader")
	proto.RegisterType((*File)(nil), "proto.File")
	proto.RegisterType((*DebugMessage)(nil), "proto.DebugMessage")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() {
	proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e)
}

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdd, 0x8a, 0xd3, 0x50,
	0x10, 0xc7, 0x9b, 0x36, 0xe9, 0x6e, 0x27, 0x45, 0xc3, 0x08, 0x12, 0xa2, 0xb0, 0xdd, 0x83, 0x60,
	0xf1, 0x22, 0x8b, 0xa9, 0x7a, 0xe1, 0x85, 0x17, 0xea, 0x8a, 0x20, 0x56, 0x38, 0x5b, 0x11, 0xaf,
	0x96, 0xb4, 0x99, 0x8d, 0x81, 0x36, 0x27, 0x24, 0x67, 0x0b, 0x79, 0x04, 0x7d, 0x4e, 0x1f, 0x44,
	0xce, 0xe4, 0xc3, 0xe2, 0xae, 0x7b, 0x95, 0xf9, 0xf8, 0x4f, 0xce, 0xcc, 0x6f, 0x06, 0x5c, 0xda,
	0x53, 0xae, 0xc3, 0xa2, 0x54, 0x5a, 0xa1, 0xc3, 0x9f, 0xe0, 0x24, 0x55, 0x2a, 0xdd, 0xd2, 0x19,
	0x7b, 0xeb, 0xeb, 0xab, 0x33, 0x9d, 0xed, 0xa8, 0xd2, 0xf1, 0xae, 0x68, 0x74, 0xc1, 0xa3, 0x7f,
	0x05, 0xb4, 0x2b, 0x74, 0xdd, 0x24, 0xc5, 0x77, 0x70, 0xce, 0xcd, 0x3f, 0xf1, 0x19, 0x8c, 0x7f,
	0x50, 0x9c, 0x50, 0xe9, 0x5b, 0x33, 0x6b, 0xee, 0x46, 0xd8, 0x08, 0x42, 0xce, 0x7e, 0xe4, 0x8c,
	0x6c, 0x15, 0xf8, 0x04, 0xec, 0xb5, 0x4a, 0x6a, 0x7f, 0xc8, 0x4a, 0xef, 0x50, 0xf9, 0x56, 0x25,
	0xb5, 0xe4, 0xac, 0x08, 0x61, 0xd2, 0x87, 0xf0, 0x14, 0x9c, 0xab, 0x6c, 0x4b, 0x95, 0x6f, 0xcd,
	0x46, 0x73, 0x37, 0x72, 0xdb, 0x9a, 0x0f, 0xd9, 0x96, 0x64, 0x93, 0x11, 0xbf, 0x86, 0xe0, 0x1e,
	0xbc, 0x86, 0x3e, 0x1c, 0xed, 0xa9, 0xac, 0x32, 0x95, 0x73, 0x4b, 0x8e, 0xec, 0x5c, 0x3c, 0x01,
	0x37, 0xa1, 0x7d, 0xb6, 0xa1, 0xcb, 0x8d, 0x4a, 0x88, 0xdb, 0x98, 0x48, 0x68, 0x42, 0xef, 0x54,
	0x42, 0x18, 0x82, 0x9d, 0xc4, 0x9a, 0xfc, 0x11, 0x37, 0x18, 0x84, 0x0d, 0x81, 0xb0, 0x23, 0x10,
	0xae, 0x3a, 0x44, 0x92, 0x75, 0xf8, 0x1a, 0x26, 0x4c, 0x76, 0x55, 0x17, 0xe4, 0xdb, 0x33, 0x6b,
	0x7e, 0x2f, 0x7a, 0x7c, 0x73, 0xfe, 0xc6, 0x36, 0x1a, 0xf9, 0x57, 0x2e, 0x56, 0xed, 0x98, 0xc6,
	0x41, 0x17, 0x8e, 0xbe, 0x2e, 0x3f, 0x2d, 0xbf, 0x7c, 0x5b, 0x7a, 0x03, 0x04, 0x18, 0x73, 0xe6,
	0xb9, 0x67, 0xf5, 0x76, 0xe4, 0x0d, 0x7b, 0x7b, 0xe1, 0x8d, 0x7a, 0xfb, 0x85, 0x67, 0xf7, 0xf6,
	0x4b, 0xcf, 0x11, 0x3f, 0x2d, 0xb0, 0x0d, 0x1c, 0x3c, 0x85, 0xe9, 0x46, 0xe5, 0x9a, 0x72, 0x7d,
	0xa9, 0x4d, 0x77, 0x0d, 0x0a, 0xb7, 0x8d, 0xf1, 0xa3, 0x21, 0xd8, 0x66, 0xe7, 0xed, 0x3a, 0xee,
	0x9c, 0xd6, 0xe8, 0x30, 0x80, 0xe3, 0x4d, 0xac, 0x29, 0x55, 0x65, 0xcd, 0x84, 0x1c, 0xd9, 0xfb,
	0x88, 0x4c, 0x2e, 0x66, 0x08, 0x53, 0xa6, 0x13, 0x8b, 0x39, 0x4c, 0xdf, 0xd3, 0xfa, 0x3a, 0xfd,
	0x4c, 0x55, 0x15, 0xa7, 0x64, 0x16, 0xb3, 0x6b, 0x4c, 0xee, 0x66, 0x22, 0x3b, 0x57, 0x00, 0x1c,
	0x4b, 0xaa, 0x0a, 0x95, 0x57, 0x14, 0xfd, 0xb6, 0x60, 0xca, 0xe3, 0x5c, 0x50, 0x69, 0x16, 0x83,
	0x4f, 0xc1, 0xbe, 0xa0, 0x3c, 0xc1, 0xe9, 0x21, 0xd9, 0xe0, 0x7e, 0xeb, 0x75, 0x75, 0x62, 0x80,
	0x0b, 0x00, 0x23, 0x6c, 0xcf, 0xe0, 0x96, 0x43, 0xbc, 0xad, 0xe8, 0x0d, 0x80, 0xa4, 0x8a, 0x34,
	0x77, 0x8a, 0x0f, 0x6f, 0x40, 0x38, 0x37, 0x47, 0x1f, 0xfc, 0x27, 0x2e, 0x06, 0xf8, 0x0a, 0x9c,
	0xbb, 0x4b, 0x1f, 0xb4, 0x6f, 0x1e, 0xa2, 0x10, 0x83, 0xf5, 0x98, 0xa3, 0x8b, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xa9, 0x77, 0x81, 0x40, 0x9b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	Send(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error)
	SendHeader(ctx context.Context, in *EventHeader, opts ...grpc.CallOption) (*Response, error)
	ResetDebug(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	Debug(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DebugMessage, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Send(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.EventService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SendHeader(ctx context.Context, in *EventHeader, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.EventService/SendHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ResetDebug(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.EventService/ResetDebug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Debug(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DebugMessage, error) {
	out := new(DebugMessage)
	err := c.cc.Invoke(ctx, "/proto.EventService/Debug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	Send(context.Context, *Event) (*Response, error)
	SendHeader(context.Context, *EventHeader) (*Response, error)
	ResetDebug(context.Context, *empty.Empty) (*empty.Empty, error)
	Debug(context.Context, *empty.Empty) (*DebugMessage, error)
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) Send(ctx context.Context, req *Event) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedEventServiceServer) SendHeader(ctx context.Context, req *EventHeader) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeader not implemented")
}
func (*UnimplementedEventServiceServer) ResetDebug(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetDebug not implemented")
}
func (*UnimplementedEventServiceServer) Debug(ctx context.Context, req *empty.Empty) (*DebugMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Debug not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Send(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SendHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventHeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SendHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/SendHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SendHeader(ctx, req.(*EventHeader))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ResetDebug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ResetDebug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/ResetDebug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ResetDebug(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/Debug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Debug(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _EventService_Send_Handler,
		},
		{
			MethodName: "SendHeader",
			Handler:    _EventService_SendHeader_Handler,
		},
		{
			MethodName: "ResetDebug",
			Handler:    _EventService_ResetDebug_Handler,
		},
		{
			MethodName: "Debug",
			Handler:    _EventService_Debug_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
