// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventHeader_RiskLevel int32

const (
	EventHeader_UNKNOWN  EventHeader_RiskLevel = 0
	EventHeader_LOW      EventHeader_RiskLevel = 1
	EventHeader_GUARDED  EventHeader_RiskLevel = 2
	EventHeader_ELEVATED EventHeader_RiskLevel = 3
	EventHeader_HIGH     EventHeader_RiskLevel = 4
	EventHeader_SEVERE   EventHeader_RiskLevel = 5
)

var EventHeader_RiskLevel_name = map[int32]string{
	0: "UNKNOWN",
	1: "LOW",
	2: "GUARDED",
	3: "ELEVATED",
	4: "HIGH",
	5: "SEVERE",
}

var EventHeader_RiskLevel_value = map[string]int32{
	"UNKNOWN":  0,
	"LOW":      1,
	"GUARDED":  2,
	"ELEVATED": 3,
	"HIGH":     4,
	"SEVERE":   5,
}

func (x EventHeader_RiskLevel) String() string {
	return proto.EnumName(EventHeader_RiskLevel_name, int32(x))
}

func (EventHeader_RiskLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2, 0}
}

type Event struct {
	Header               *EventHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *EventBody   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetHeader() *EventHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Event) GetBody() *EventBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type EventBody struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventBody) Reset()         { *m = EventBody{} }
func (m *EventBody) String() string { return proto.CompactTextString(m) }
func (*EventBody) ProtoMessage()    {}
func (*EventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *EventBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventBody.Unmarshal(m, b)
}
func (m *EventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventBody.Marshal(b, m, deterministic)
}
func (m *EventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBody.Merge(m, src)
}
func (m *EventBody) XXX_Size() int {
	return xxx_messageInfo_EventBody.Size(m)
}
func (m *EventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBody.DiscardUnknown(m)
}

var xxx_messageInfo_EventBody proto.InternalMessageInfo

func (m *EventBody) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type EventHeader struct {
	Version              int32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Date                 *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	RiskLevel            EventHeader_RiskLevel `protobuf:"varint,3,opt,name=riskLevel,proto3,enum=proto.EventHeader_RiskLevel" json:"riskLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EventHeader) Reset()         { *m = EventHeader{} }
func (m *EventHeader) String() string { return proto.CompactTextString(m) }
func (*EventHeader) ProtoMessage()    {}
func (*EventHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *EventHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventHeader.Unmarshal(m, b)
}
func (m *EventHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventHeader.Marshal(b, m, deterministic)
}
func (m *EventHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventHeader.Merge(m, src)
}
func (m *EventHeader) XXX_Size() int {
	return xxx_messageInfo_EventHeader.Size(m)
}
func (m *EventHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_EventHeader.DiscardUnknown(m)
}

var xxx_messageInfo_EventHeader proto.InternalMessageInfo

func (m *EventHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EventHeader) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *EventHeader) GetRiskLevel() EventHeader_RiskLevel {
	if m != nil {
		return m.RiskLevel
	}
	return EventHeader_UNKNOWN
}

type File struct {
	ContentType          int32                `protobuf:"varint,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Category             int32                `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	Data                 []byte               `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetContentType() int32 {
	if m != nil {
		return m.ContentType
	}
	return 0
}

func (m *File) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *File) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.EventHeader_RiskLevel", EventHeader_RiskLevel_name, EventHeader_RiskLevel_value)
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*EventBody)(nil), "proto.EventBody")
	proto.RegisterType((*EventHeader)(nil), "proto.EventHeader")
	proto.RegisterType((*File)(nil), "proto.File")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() {
	proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e)
}

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0xa3, 0x58, 0xf2, 0x9f, 0x91, 0x68, 0xc5, 0xd0, 0x83, 0x30, 0x85, 0x2a, 0xa2, 0x50,
	0xd3, 0xc3, 0x06, 0x9c, 0x5b, 0x6f, 0x29, 0xde, 0xc6, 0xa5, 0xc6, 0x81, 0xb5, 0x93, 0xd0, 0x53,
	0x91, 0xad, 0x89, 0x2b, 0xaa, 0x68, 0xc5, 0x6a, 0x2b, 0xd0, 0x23, 0xf4, 0x49, 0xfb, 0x1a, 0x45,
	0x2b, 0xc9, 0x35, 0x34, 0x87, 0x9e, 0xc4, 0xf7, 0xcd, 0x6f, 0xb4, 0xfb, 0xcd, 0x0e, 0xb8, 0x54,
	0x51, 0xae, 0x59, 0xa1, 0xa4, 0x96, 0xe8, 0x98, 0xcf, 0xf4, 0xcd, 0x41, 0xca, 0x43, 0x46, 0x97,
	0x46, 0xed, 0x7e, 0x3e, 0x5e, 0xea, 0xf4, 0x89, 0x4a, 0x1d, 0x3f, 0x15, 0x2d, 0x17, 0x7d, 0x05,
	0x87, 0x37, 0x6d, 0xf8, 0x1e, 0x86, 0xdf, 0x29, 0x4e, 0x48, 0x05, 0x56, 0x68, 0xcd, 0xdc, 0x39,
	0xb6, 0x00, 0x33, 0xd5, 0xa5, 0xa9, 0x88, 0x8e, 0xc0, 0xb7, 0x60, 0xef, 0x64, 0x52, 0x07, 0xe7,
	0x86, 0xf4, 0x4f, 0xc9, 0x8f, 0x32, 0xa9, 0x85, 0xa9, 0x46, 0x0c, 0x26, 0x47, 0x0b, 0x2f, 0xc0,
	0x79, 0x4c, 0x33, 0x2a, 0x03, 0x2b, 0x1c, 0xcc, 0xdc, 0xb9, 0xdb, 0xf5, 0x7c, 0x4a, 0x33, 0x12,
	0x6d, 0x25, 0xfa, 0x6d, 0x81, 0x7b, 0x72, 0x1a, 0x06, 0x30, 0xaa, 0x48, 0x95, 0xa9, 0xcc, 0xcd,
	0x95, 0x1c, 0xd1, 0x4b, 0x64, 0x60, 0x27, 0xb1, 0xa6, 0xee, 0xfc, 0x29, 0x6b, 0x43, 0xb2, 0x3e,
	0x24, 0xdb, 0xf6, 0x21, 0x85, 0xe1, 0xf0, 0x03, 0x4c, 0x54, 0x5a, 0xfe, 0x58, 0x51, 0x45, 0x59,
	0x30, 0x08, 0xad, 0xd9, 0x8b, 0xf9, 0xeb, 0x7f, 0xe3, 0x31, 0xd1, 0x33, 0xe2, 0x2f, 0x1e, 0x09,
	0x98, 0x1c, 0x7d, 0x74, 0x61, 0x74, 0xb7, 0xfe, 0xb2, 0xbe, 0x7d, 0x58, 0xfb, 0x67, 0x38, 0x82,
	0xc1, 0xea, 0xf6, 0xc1, 0xb7, 0x1a, 0xf7, 0xe6, 0xee, 0x5a, 0x2c, 0xf8, 0xc2, 0x3f, 0x47, 0x0f,
	0xc6, 0x7c, 0xc5, 0xef, 0xaf, 0xb7, 0x7c, 0xe1, 0x0f, 0x70, 0x0c, 0xf6, 0xf2, 0xf3, 0xcd, 0xd2,
	0xb7, 0x11, 0x60, 0xb8, 0xe1, 0xf7, 0x5c, 0x70, 0xdf, 0x89, 0x7e, 0x59, 0x60, 0x37, 0xc9, 0xf1,
	0x02, 0xbc, 0xbd, 0xcc, 0x35, 0xe5, 0xfa, 0x9b, 0xae, 0x0b, 0xea, 0x72, 0xba, 0x9d, 0xb7, 0xad,
	0x0b, 0x6a, 0xb2, 0x36, 0x6f, 0xf6, 0x3f, 0x59, 0x1b, 0x0e, 0xa7, 0x30, 0xde, 0xc7, 0x9a, 0x0e,
	0x52, 0xd5, 0x26, 0xaa, 0x23, 0x8e, 0x1a, 0xd1, 0xcc, 0x2d, 0x0e, 0xec, 0xd0, 0x9a, 0x79, 0x66,
	0x36, 0x71, 0x14, 0xc2, 0x58, 0x50, 0x59, 0xc8, 0xbc, 0x24, 0x7c, 0x05, 0x0e, 0x29, 0x25, 0xdb,
	0x15, 0x98, 0x88, 0x56, 0xcc, 0x33, 0xf0, 0xcc, 0x94, 0x36, 0xa4, 0xaa, 0x74, 0x4f, 0xf8, 0x0e,
	0xec, 0x0d, 0xe5, 0x09, 0x7a, 0xa7, 0x23, 0x9c, 0xbe, 0xec, 0x54, 0xff, 0xb3, 0xe8, 0x0c, 0xaf,
	0x00, 0x1a, 0xb0, 0x7b, 0xce, 0x67, 0x16, 0xea, 0x99, 0xa6, 0xdd, 0xd0, 0x38, 0x57, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x44, 0xdf, 0x05, 0x15, 0xce, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	Send(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error)
	SendHeader(ctx context.Context, in *EventHeader, opts ...grpc.CallOption) (*Response, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Send(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.EventService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SendHeader(ctx context.Context, in *EventHeader, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.EventService/SendHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	Send(context.Context, *Event) (*Response, error)
	SendHeader(context.Context, *EventHeader) (*Response, error)
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) Send(ctx context.Context, req *Event) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedEventServiceServer) SendHeader(ctx context.Context, req *EventHeader) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeader not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Send(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SendHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventHeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SendHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/SendHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SendHeader(ctx, req.(*EventHeader))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _EventService_Send_Handler,
		},
		{
			MethodName: "SendHeader",
			Handler:    _EventService_SendHeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
